[tool.pytest.ini_options]
pythonpath = [
    ".", "src"
]

addopts = "--cov=src --cov-report=term-missing --cov-fail-under=80 --cov-config=pyproject.toml"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
omit = [
    "src/main.py",
    "src/config.py"
]
show_missing = true